# Generated by Django 3.2.14 on 2022-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=50, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'autores',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=200, null=True)),
                ('anticipo', models.DecimalField(blank=True, db_column='Anticipo', decimal_places=2, max_digits=19, null=True)),
                ('pago', models.CharField(blank=True, db_column='Pago', max_length=100, null=True)),
                ('genero', models.CharField(blank=True, db_column='Genero', max_length=100, null=True)),
                ('ebook', models.CharField(blank=True, db_column='Ebook', max_length=10, null=True)),
                ('xciento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libros',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('mercado', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('totales', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('reporte', models.IntegerField(blank=True, db_column='Reporte', null=True)),
                ('cobrado', models.IntegerField(blank=True, db_column='Cobrado', null=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['fecha'],
                'managed': False,
            },
        ),
    ]
